services:
  bookify-api:
    image: bookify.api
    container_name: Bookify.Api
    build:
      context: .
      dockerfile: Bookify.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=pa55wOrd!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Bookify.Api.pfx
    ports:
      - "80"
      - 5001:443
    volumes:
      - ${USERPROFILE}\.aspnet\https:/https:ro
    depends_on:
      - bookify-db
    restart: always
  
  
  bookify-db:
    image: postgres:latest
    container_name: Bookify.Db
    environment:
      - POSTGRES_DB=bookify
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5434:5432
    restart: always
    
volumes:
  pgdata: { }