services:
  bookify.api:
    image: bookify.api
    build:
      context: .
      dockerfile: Bookify.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=pa55wOrd!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Bookify.Api.pfx
    ports:
      - "80"
      - 5001:443
    volumes:
      - ${USERPROFILE}\.aspnet\https:/https:ro
    depends_on: 
      - bookify-db
  
  bookify-db:
    image: postgres:latest
    container_name: Bookify.Db
    environment:
      - POSTGRES_DB=bookify
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/database:/var/lib/postgresql/data
    ports:
      - 5432:5432
